version: '3.8'

services:
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mydbserver.postgres.database.azure.com
      - DB_PORT=5432
      - DB_NAME=your_database_name
      - DB_USER=thisaraniii
      - DB_PASSWORD=deakin1234@@
    depends_on:
      - inventory_management

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=mydbserver.postgres.database.azure.com
      - DB_PORT=5432
      - DB_NAME=your_database_name
      - DB_USER=thisaraniii
      - DB_PASSWORD=deakin1234@@

networks:
  default:
    external: false
